/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban;

import SubGUI.GoiMonGUI;
import SubGUI.XuatThongTinGUI;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MonAn;
import services.ChonBanService;
import services.GoiMonService;

/**
 *
 * @author truon
 */
public class ChonBanJPanel extends javax.swing.JPanel {
    
    private final ChonBanService chonBanService = new ChonBanService();
    private final GoiMonService goiMonService = new GoiMonService();
    private DefaultTableModel dtmDanhSachOrder;
    private String BanDangChon = "1";
    private int rowSelected = -1;
    private int BanSo;
    /**
     * Creates new form ChonBanJPanel
     */
    public ChonBanJPanel() {
        initComponents();
        // Khởi tạo DefaultTableModel cho bảng
        dtmDanhSachOrder = new javax.swing.table.DefaultTableModel(
            new Object[][]{}, // Dữ liệu ban đầu rỗng
            new String[]{"Mã Món", "Tên Món", "Đơn Giá", "Số Lượng"} // Tên cột
        );
        // Gán DefaultTableModel cho bảng
        DanhSachOrder.setModel(dtmDanhSachOrder);
        CapNhapStatusBan(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        SelectBan = new javax.swing.JComboBox<>();
        pnStatusBan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblStatusBan = new javax.swing.JLabel();
        Decorate1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBanSo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DanhSachOrder = new javax.swing.JTable();
        ThemMon = new javax.swing.JButton();
        XoaMon = new javax.swing.JButton();
        ThanhToan = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        Container.setBackground(new java.awt.Color(204, 255, 255));
        Container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Container.setPreferredSize(new java.awt.Dimension(645, 440));

        SelectBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bàn 1", "Bàn 2", "Bàn 3", "Bàn 4", "Bàn 5", "Bàn 6", "Bàn 7  ", "Bàn 8 ", "Bàn 9" }));
        SelectBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBanActionPerformed(evt);
            }
        });

        pnStatusBan.setBackground(new java.awt.Color(50, 240, 50));
        pnStatusBan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 3, true));
        pnStatusBan.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setText("Trạng Thái Bàn:");

        lblStatusBan.setText("Trống");

        javax.swing.GroupLayout pnStatusBanLayout = new javax.swing.GroupLayout(pnStatusBan);
        pnStatusBan.setLayout(pnStatusBanLayout);
        pnStatusBanLayout.setHorizontalGroup(
            pnStatusBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatusBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblStatusBan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnStatusBanLayout.setVerticalGroup(
            pnStatusBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatusBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatusBan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Decorate1.setBackground(new java.awt.Color(102, 255, 204));
        Decorate1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Thực Đơn Bàn Số :");

        lblBanSo.setText("1");

        javax.swing.GroupLayout Decorate1Layout = new javax.swing.GroupLayout(Decorate1);
        Decorate1.setLayout(Decorate1Layout);
        Decorate1Layout.setHorizontalGroup(
            Decorate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decorate1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanSo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Decorate1Layout.setVerticalGroup(
            Decorate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Decorate1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Decorate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBanSo)))
        );

        DanhSachOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DanhSachOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Món", "Tên Món", "Số lượng", "Đơn Giá"
            }
        ));
        jScrollPane1.setViewportView(DanhSachOrder);

        ThemMon.setBackground(new java.awt.Color(102, 255, 102));
        ThemMon.setText("Thêm món");
        ThemMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemMonActionPerformed(evt);
            }
        });

        XoaMon.setBackground(new java.awt.Color(255, 51, 0));
        XoaMon.setText("Xóa Món");
        XoaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaMonActionPerformed(evt);
            }
        });

        ThanhToan.setBackground(new java.awt.Color(51, 255, 204));
        ThanhToan.setText("Thanh Toán");
        ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThanhToanActionPerformed(evt);
            }
        });

        btnXuatHoaDon.setBackground(new java.awt.Color(255, 204, 255));
        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        btnReload.setBackground(new java.awt.Color(204, 255, 255));
        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnStatusBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Decorate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectBan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ThemMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(XoaMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Decorate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ThemMon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(XoaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnStatusBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBanActionPerformed
        // TODO add your handling code here:
        BanSo = SelectBan.getSelectedIndex();
        lblBanSo.setText(String.valueOf(BanSo+1));
        ShowDanhSachOrder(String.valueOf(BanSo+1));
        CapNhapStatusBan(BanSo+1);
        BanDangChon = String.valueOf(BanSo+1);

    }//GEN-LAST:event_SelectBanActionPerformed

    private void ThemMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemMonActionPerformed
//        System.out.println(BanDangChon);
        GoiMonGUI goiMonGUI = new GoiMonGUI(BanDangChon, pnStatusBan);
        goiMonGUI.showWindow(ChonBanJPanel.this);
    }//GEN-LAST:event_ThemMonActionPerformed

    private void XoaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaMonActionPerformed
        rowSelected = DanhSachOrder.getSelectedRow();
            if (rowSelected != -1) {
                goiMonService.xoaMonAn(BanDangChon, String.valueOf(dtmDanhSachOrder.getValueAt(rowSelected, 0)));
                ShowDanhSachOrder(BanDangChon);
                CapNhapStatusBan(BanSo);
            } else {
                if (goiMonService.laySoLuongMonAn(BanDangChon) > 0) {
                    JOptionPane.showMessageDialog(ChonBanJPanel.this, "Vui lòng chọn món ăn cần xóa!");
                } else {
                    JOptionPane.showMessageDialog(ChonBanJPanel.this, "Không có gì để xóa!");
                }
            }
    }//GEN-LAST:event_XoaMonActionPerformed

    private void ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThanhToanActionPerformed
        if (!BanDangChon.equals("#")) {
                if (dtmDanhSachOrder.getRowCount() > 0) {
                    int chon = JOptionPane.showConfirmDialog(ChonBanJPanel.this, "Xác nhận đã thanh toán", "Confirm", JOptionPane.OK_CANCEL_OPTION);
                    if (chon == JOptionPane.OK_OPTION) {
                        
                        goiMonService.xoaMonAn(BanDangChon);
                        ShowDanhSachOrder(BanDangChon);
                    }
                } else {
                    JOptionPane.showMessageDialog(ChonBanJPanel.this, "Bàn ăn đang trống!");
                }
            } 
    }//GEN-LAST:event_ThanhToanActionPerformed

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        Vector<MonAn> dsThucDon = goiMonService.layDsThucDonTheoBan(BanDangChon);
                if (dsThucDon.size() > 0) {
                    XuatThongTinGUI xuatThongTinGUI = new XuatThongTinGUI(BanDangChon, dsThucDon);
                    xuatThongTinGUI.showWindow(ChonBanJPanel.this);
                } else {
                    JOptionPane.showMessageDialog(ChonBanJPanel.this, "Bàn ăn đang trống!");
                }
            
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        CapNhapStatusBan(BanSo+1);
        ShowDanhSachOrder(String.valueOf(BanSo+1));
    }//GEN-LAST:event_btnReloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JTable DanhSachOrder;
    private javax.swing.JPanel Decorate1;
    private javax.swing.JComboBox<String> SelectBan;
    private javax.swing.JButton ThanhToan;
    private javax.swing.JButton ThemMon;
    private javax.swing.JButton XoaMon;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanSo;
    private javax.swing.JLabel lblStatusBan;
    private javax.swing.JPanel pnStatusBan;
    // End of variables declaration//GEN-END:variables
    
    private void ShowDanhSachOrder(String BanSo) {
        Vector<MonAn> DanhSachOrder = chonBanService.getDanhSachOrder(BanSo);
        dtmDanhSachOrder.setRowCount(0);
        
        DecimalFormat df = new DecimalFormat("#,###");
        for (MonAn monAn : DanhSachOrder) {
            Vector<Object> vec = new Vector<>();
            vec.add(monAn.getMaMonAn());
            vec.add(monAn.getTenMonAn());
            vec.add(df.format(monAn.getDonGia()));
            vec.add(monAn.getSoLuong());
//            vec.add(df.format((long) monAn.getDonGia() * monAn.getSoLuong()));
            dtmDanhSachOrder.addRow(vec);
        }  
    }
    
    private void CapNhapStatusBan(int BanSo) {
        if (chonBanService.laySoLuongMonAn(String.valueOf(BanSo)) > 0) {
            chonBanService.setStatusBan(String.valueOf(BanSo),"busy");
        } else {
            chonBanService.setStatusBan(String.valueOf(BanSo),"Empty");
        }
        if (chonBanService.getStatusBan(String.valueOf(BanSo)).equalsIgnoreCase("Empty")) {
                    pnStatusBan.setBackground(Color.GREEN);
                    lblStatusBan.setText("Trống");
                } else {
                    pnStatusBan.setBackground(Color.RED);
                    lblStatusBan.setText("Bận rộn");
                }
    }
}

