/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import model.HoaDon;
import services.HoaDonService;





/**
 *
 * @author truon
 */
public class HoaDonJPanel extends javax.swing.JPanel {
    
    private HoaDonService hoaDonService = new HoaDonService();
    private javax.swing.table.DefaultTableModel dtmHoaDon;
    private Vector<HoaDon> dsHoaDon;

    /**
     * Creates new form HoaDonJPanel
     */
    public HoaDonJPanel() {
        initComponents();
        dtmHoaDon = new javax.swing.table.DefaultTableModel(
                new Object[][]{}, // Dữ liệu ban đầu rỗng
                new String[]{"Mã Hóa Đơn", "Bàn Số", "Tổng Tiền", "Thời gian"} // Tên cột
        );
//        Calendar calendar = Calendar.getInstance();
//        System.out.print(String.valueOf(calendar.get(Calendar.DAY_OF_MONTH)));
        // Gán DefaultTableModel cho bảng
        tblHoaDon.setModel(dtmHoaDon);
        hienThiHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHoaDon = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnDoanhThuNgay = new javax.swing.JButton();
        btnDoanhThuThang = new javax.swing.JButton();
        txtNgay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtThang = new javax.swing.JTextField();

        Container.setBackground(new java.awt.Color(255, 204, 204));
        Container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(0, 102, 102));
        lblHoaDon.setText("Hóa Đơn");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setText("Lọc hóa đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tblHoaDon.setBackground(new java.awt.Color(255, 153, 153));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Bàn", "Tổng Tiền", "Thời Gian"
            }
        ));
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDoanhThuNgay.setText("Doanh thu ngày");
        btnDoanhThuNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuNgayActionPerformed(evt);
            }
        });

        btnDoanhThuThang.setText("Doanh Thu Tháng");
        btnDoanhThuThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuThangActionPerformed(evt);
            }
        });

        txtNgay.setText("01");

        jLabel2.setText("Ngày:");

        jLabel3.setText("Tháng:");

        txtThang.setText("01");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoanhThuNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoanhThuThang)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDoanhThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDoanhThuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                locThongTin();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                locThongTin();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                locThongTin();
            }
        });
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnDoanhThuNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuNgayActionPerformed
        String ngayChon = txtNgay.getText();
        String thangChon = txtThang.getText();
        // Gọi hàm để tính tổng tiền theo ngày
        double tongTien = tinhTongTienTheoNgay(ngayChon, thangChon);
        // Hiển thị kết quả trong dialog
        JOptionPane.showMessageDialog(this, "Tổng tiền trong ngày " + ngayChon + "-"+ thangChon +": " + tongTien + "đ");
    }//GEN-LAST:event_btnDoanhThuNgayActionPerformed

    private void btnDoanhThuThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuThangActionPerformed
        String thangChon = txtThang.getText();
      
        double tongTien = tinhTongTienTheoThang(thangChon);
        // Hiển thị kết quả trong dialog
        JOptionPane.showMessageDialog(this, "Tổng tiền trong Tháng " + thangChon +" : " + tongTien + "đ");
    }//GEN-LAST:event_btnDoanhThuThangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton btnDoanhThuNgay;
    private javax.swing.JButton btnDoanhThuThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtThang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void hienThiHoaDon() {
        docDuLieu();
        dtmHoaDon.setRowCount(0);
        for (HoaDon hoaDon : dsHoaDon) {
            Vector<Object> vec = new Vector<>();
            vec.add(hoaDon.getMaHoaDon());
            vec.add(hoaDon.getBanSo());
            vec.add(hoaDon.getTongTien());
            vec.add(hoaDon.getthoigian());
            dtmHoaDon.addRow(vec);
        }
    }

    
    private void hienThiHoaDon(Vector<HoaDon> dsHoaDonDaLoc) {
        dtmHoaDon.setRowCount(0);
        for (HoaDon hoaDon : dsHoaDonDaLoc) {
            Vector<Object> vec = new Vector<>();
            vec.add(hoaDon.getMaHoaDon());
            vec.add(hoaDon.getBanSo());
            vec.add(hoaDon.getTongTien());
            vec.add(hoaDon.getthoigian());
            dtmHoaDon.addRow(vec);
        }
    }
    
    
    private void docDuLieu() {
        dsHoaDon = hoaDonService.layDanhSachHoaDon();
    }
    
    public void locThongTin() {
        docDuLieu();
        String duLieuLoc = txtTimKiem.getText();
        Vector<HoaDon> dsHoaDonDaLoc = new Vector<>();
        for (HoaDon hoaDon : dsHoaDon) {
            if (String.valueOf(hoaDon.getMaHoaDon()).toUpperCase().contains(duLieuLoc.trim().toUpperCase())
                    || hoaDon.getBanSo().toUpperCase().contains(duLieuLoc.trim().toUpperCase()) 
                    || hoaDon.getthoigian().toUpperCase().contains(duLieuLoc.trim().toUpperCase()))
                {
                dsHoaDonDaLoc.add(hoaDon);
            }
        }
        if (duLieuLoc.trim().length() > 0) {
            hienThiHoaDon(dsHoaDonDaLoc);
        } else {
            hienThiHoaDon();
        }
    }
    
    public int tinhTongTienTheoNgay(String ngayChon, String thangChon) {
        int tongTien = 0;
        for (HoaDon hoaDon : dsHoaDon) {
            // Lấy ngày từ trường thoigian của hóa đơn
            String ngayHoaDon = hoaDon.getthoigian().substring(0, 10);
            String ngayHoaDonStr = ngayHoaDon.substring(8, 10);
            String thangHoaDonStr = ngayHoaDon.substring(5, 7);
            if (ngayHoaDonStr.equals(ngayChon) && thangHoaDonStr.equals(thangChon)) {
                // Cộng tổng tiền của hóa đơn vào tổng tiền chung
                tongTien += hoaDon.getTongTien();
            }
        }
        return tongTien;
    }
    public int tinhTongTienTheoThang(String thangChon) {
        int tongTien = 0;
        for (HoaDon hoaDon : dsHoaDon) {
            // Lấy ngày từ trường thoigian của hóa đơn
            String ngayHoaDon = hoaDon.getthoigian().substring(0, 10);
            String thangHoaDonStr = ngayHoaDon.substring(5, 7);
            if (thangHoaDonStr.equals(thangChon)) {
                // Cộng tổng tiền của hóa đơn vào tổng tiền chung
                tongTien += hoaDon.getTongTien();
            }
        }
        return tongTien;
    }
}
